[project]
name = "reprise"
requires-python = ">= 3.11"
dynamic = ["version"]

dependencies = [
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "alembic",
    "openai",
    "requests",
    "pydantic-ai-slim[openai]",
    "logfire"
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "pytest-cov",
    "pytest-env",
    "factory-boy"
]

[tool.setuptools]
packages = ["reprise"]

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "C", "N", "Q", "B"]
lint.ignore = ["E501"]

[tool.pytest.ini_options]
env = [
    "DATABASE_URL=sqlite:///:memory:",
]
